name: 'Build: Backend Java Apps'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*


permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build --console=plain --scan


      - name: Run Astronuts Code Quality Checks
        uses: astronuts-app/astronuts-code-quality-action@v3
        with:
          sourceLanguage: 'java'
          buildSystem: 'gradle'
#          failOnError: true
#          serverUrl: ${{ vars.HELIOS_SERVER_URL }}