name: 'Build: Backend Java Apps'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
  pull_request:
    branches:
      - main


permissions:
  contents: read
  pull-requests: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build --console=plain --scan
      - name: Run Astronuts Code Quality Checks
        uses: astronuts-app/astronuts-ai@v2.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prReview: true
          prWalkthrough: true
          staticAnalysis: true
        
          
